package template

import (
	"bytes"
	"text/template"

	"github.com/mortenskoett/dotf-go/pkg/parsing"
)

const (
	autoGeneratedText = `### DOTFILES AUTOGENERATED ENVVARS ###`
)

// Templates.
const (
	bash_profile = `
#
# {{.DistroName}} specific ~/.bash_profile
#

{{.AutoGeneratedText}}
# export DOTFILES="{{.UserspaceDir}}/dotfiles"
# export DOTFILES_DISTRO_NAME="{{.DistroName}}"
# export DOTFILES_DISTRO="${DOTFILES}/distros/${DOTFILES_DISTRO_NAME}/dotfiles"
# export DOTFILES_SHARED="$DOTFILES/shared"

# Bash
if [[ -f ${HOME}/.bashrc ]]; then
	source ${HOME}/.bashrc
else
	echo ".bashrc not found at '${HOME}/.bashrc' by .bash_profile"
fi`
)

func GenerateBashProfile(conf *parsing.DotfConfiguration) ([]byte, error) {
	tmpl, err := template.New("bashProfile").Parse(bash_profile)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer

	err = tmpl.Execute(&buf, &conf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
